# User configuration:

SRCDIR = $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)
CONFDIR = $(SRCDIR)/config
LIBDIR = $(SRCDIR)/lib/pyctf
BINDIR = $(SRCDIR)/bin

CFLAGS = -I. -O2 -Wunused -fPIC
LDFLAGS = -lm -lfftw3

CC = gcc
AR = ar

make: all

clean-x:
	for x in $(targets) ; do \
		$(MAKE) -C $$x $@ || exit ;\
	done
	rm -f *~ *.pyc *.o *.a *.so
	rm -fr __pycache__
